server:
      port: 7011
eureka:
      instance:
              hostname: peer2
      client:
            serviceUrl:
                    defaultZone: http://localhost:7010/eureka/
spring:
  application:
            name: eureka-server