server:
      port: 7010
eureka:
      instance:
              hostname: peer1
      client:
            serviceUrl:
                    defaultZone: http://localhost:7011/eureka/
spring:
  application:
            name: eureka-server